Create base Progress component
SprocketBot/sprocket-ui pull request #3
Opened 2021-07-14 13:28 UTC by zachstence

2021-07-14 14:51 UTC, 0c370t requested changes
Lots of magic numbers, needs an eslint pass

2021-07-14 14:51 UTC, 0c370t commented on package.json
> +    "@types/faker": "^5.5.7",
We do we have faker types installed if we don't have faker installed?

2021-07-14 14:51 UTC, 0c370t commented on src/atoms/Progress/Progress.spec.ts
> +
Empty lines at start of file

2021-07-14 14:51 UTC, 0c370t commented on src/atoms/Progress/Progress.spec.ts
> +            progress: -9999,
No Magic Numbers > 2

2021-07-14 14:51 UTC, 0c370t commented on src/atoms/Progress/Progress.spec.ts
> +            max: 10
No Magic Numbers > 2

2021-07-14 14:51 UTC, 0c370t commented on src/atoms/Progress/Progress.spec.ts
> +            max: 10
No Magic Numbers > 2

2021-07-14 14:51 UTC, 0c370t commented on src/atoms/Progress/Progress.spec.ts
> +            max: 100
No Magic Numbers > 2

2021-07-14 14:51 UTC, 0c370t commented on src/atoms/Progress/Progress.stories.svelte
> +            defaultValue: 20,
No Magic Numbers > 2

2021-07-14 14:51 UTC, 0c370t commented on src/atoms/Progress/Progress.stories.svelte
> +            defaultValue: 13,
No Magic Numbers > 2

2021-07-14 14:51 UTC, 0c370t commented on src/atoms/Progress/Progress.svelte
> +    $: width = (actualProgress / max) * 100;
No Magic Numbers > 2

2021-07-14 16:18 UTC, zachstence commented on src/atoms/Progress/Progress.spec.ts
> +
Fixed in 0f469ad

2021-07-14 16:18 UTC, zachstence commented on package.json
> +    "@types/faker": "^5.5.7",
Forgot to uninstall, fixed in 0f469ad

2021-07-16 00:43 UTC, 0c370t approved these changes

2021-07-16 00:43 UTC, merged