WIP: Create base DataTable
SprocketBot/sprocket-ui pull request #7
Opened 2021-07-19 23:07 UTC by zachstence

2021-07-20 22:59 UTC, 0c370t requested changes
Overall heading in the correct direction; few minor tweaks required, and one potential new ticket to create if we don't want to scope creep this too hard.

2021-07-20 22:59 UTC, 0c370t commented on src/atoms/DataTable/DataTable.svelte
> +    export let initialSort: SortConfig | undefined = undefined;
We probably want sort to enable sorts on multiple columns in multiple directions; however, I'm okay with putting that in it's own ticket we want to split that out.

2021-07-20 22:59 UTC, 0c370t commented on src/atoms/DataTable/DataTable.svelte
> +        [SortDirection.None]: "―",
`-` or empty string here?

2021-07-20 22:59 UTC, 0c370t commented on src/atoms/DataTable/DataTable.svelte
> +            return datum as string;
I would advocate for a `.toString` property check and throwing an error if one is not available

2021-07-21 00:34 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +        [SortDirection.None]: "―",
Needs to be a "-" so that there's something to click on when the column is not sorted. I imagined all of these sorting indicators would get replaced by icons ( like [this](https://fontawesome.com/v5.15/icons/sort) ) when we did branding

2021-07-21 00:35 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +            return datum as string;
Throwing an error is a good idea, I'll add that.
Originally I had called the property `.toString`, but this is JS and everything is an object and every object has a `.toString`, so we can't call it that

2021-07-22 12:37 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +            return datum as string;
Actually, scratch that. It can be called `.toString` if I check by using `.hasOwnProperty` instead of just `if(column.toString)`

2021-07-22 13:02 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +            return datum as string;
Resolved with 7c774ac

2021-07-22 13:12 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +    export let initialSort: SortConfig | undefined = undefined;
Hmm, this brings up some other design questions so might be best for another ticket.
- Do we need a prop on the DataTable to allow/disallow multi-column sorting?
- Do we want multi-column sorting to be the default behavior? Or do we want some kind of toggle, or maybe you have to hold down a key while clicking another column to do a multi-column sort? e.g. https://datatables.net/beta/1.8/examples/basic_init/multi_col_sort.html
- We either need a "Reset" button built in to the datatable, or a way for the user of the `<DataTable />` to tell the datatable to reset the sorting

2021-07-31 18:41 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +    export let initialSort: SortConfig | undefined = undefined;
Created Clickup ticket https://app.clickup.com/t/1ae3yhd

2021-08-01 22:45 UTC, 0c370t commented on src/atoms/DataTable/DataTable.svelte
> +    const FILTER_CLEAR_CHAR = "✖";
These should be icons eventually

2021-08-01 22:45 UTC, 0c370t commented on src/atoms/DataTable/DataTable.svelte
> +        if (Object.prototype.hasOwnProperty.call(columnConfig, "toString") && typeof columnConfig.toString === "function") {
Should we use `Object.keys().includes` here instead? May be more clear

2021-08-01 22:45 UTC, 0c370t commented on src/atoms/DataTable/DataTable.svelte
> +        } else if (Object.prototype.hasOwnProperty.call(datum, "toString") && typeof datum.toString === "function") {
ditto

2021-08-01 22:45 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +    const FILTER_CLEAR_CHAR = "✖";
Yep, the characters are just placeholders for now. When we do branding I'll refactor to use some icons

2021-08-01 22:46 UTC, 0c370t submitted a review, later dismissed
Couple minor things for the future but seems fine

2021-08-02 00:51 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +        if (Object.prototype.hasOwnProperty.call(columnConfig, "toString") && typeof columnConfig.toString === "function") {
Oh that's a good point, `Object.keys` should work fine here.

2021-08-03 00:01 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +        } else if (Object.prototype.hasOwnProperty.call(datum, "toString") && typeof datum.toString === "function") {
Fixed in 4dc741b

2021-08-03 00:01 UTC, zachstence commented on src/atoms/DataTable/DataTable.svelte
> +        if (Object.prototype.hasOwnProperty.call(columnConfig, "toString") && typeof columnConfig.toString === "function") {
Fixed in 4dc741b

2021-08-03 00:02 UTC, merged