WIP: Toast and ToastProvider
SprocketBot/sprocket-ui pull request #9
Opened 2021-08-18 02:46 UTC by zachstence

2021-08-18 02:46 UTC, zachstence commented
Toast and ToastProvider are ready to be reviewed. The stories need some more work.

2021-08-20 00:20 UTC, 0c370t requested changes

2021-08-20 00:20 UTC, 0c370t commented on src/atoms/Toast/Toast.svelte
> +    }
Should these be here or in a `types` file? Not super opinionated either way, but this does bloat the component a bit.
Also, for Variant, lets have a default case of `""`

2021-08-20 00:20 UTC, 0c370t commented on src/atoms/Toast/Toast.svelte
> +        ;
Please fix formatting

2021-08-20 00:20 UTC, 0c370t commented on src/atoms/Toast/Toast.svelte
> +        {/if}
Lets just accept HTML here; may want to consider some form of sanitization to prevent script tags, but I'm not sure what the best answer to that will be.

2021-08-20 00:20 UTC, 0c370t commented on src/atoms/Toast/ToastProvider/ToastProvider.svelte
> +    }
Move to `types` file or `context="module"` for consistency

2021-08-20 00:20 UTC, 0c370t commented on src/atoms/Toast/ToastProvider/ToastProvider.svelte
> +        return id;
Instead of returning id, maybe return destroy toast (i.e. `() => destroyToast(id)`)? Will lessen the need for contexts and be more consistent with the native svelte libraries

2021-08-20 00:20 UTC, 0c370t commented on src/utils/Dummy.svelte
> +<div>{text}</div>
Is this still required with the introduction of `svelte-htm`? Also, should we put these in a utils/tests folder to make it easier to exclude them from the build?

2021-08-20 00:33 UTC, zachstence commented on src/atoms/Toast/Toast.svelte
> +        ;
Resolved in be3d4f2

2021-08-20 00:34 UTC, zachstence commented on src/atoms/Toast/ToastProvider/ToastProvider.svelte
> +    }
Resolved in df4474d

2021-08-20 00:34 UTC, zachstence commented on src/atoms/Toast/ToastProvider/ToastProvider.svelte
> +        return id;
Resolved in ab00ca6

2021-08-20 00:34 UTC, zachstence commented on src/utils/Dummy.svelte
> +<div>{text}</div>
Resolved in e2a440e

2021-08-20 00:37 UTC, zachstence commented on src/utils/Dummy.svelte
> +<div>{text}</div>
Resolved in e2a440e and 0af6d65

2021-08-20 01:46 UTC, zachstence commented on src/atoms/Toast/Toast.svelte
> +        {/if}
Resolved in 6f9c205

2021-08-20 01:47 UTC, zachstence commented on src/atoms/Toast/Toast.svelte
> +    }
Going to leave them in here to match structure of other components.
Resolved in 5b5fe31.

2021-08-20 02:30 UTC, 0c370t approved these changes

2021-09-02 15:14 UTC, 0c370t requested changes

2021-09-02 15:14 UTC, 0c370t commented on src/atoms/Toast/Toast.svelte
> +<div class="toast {variant}" class:clickable={onClick !== undefined} on:click={onClick} on:mouseenter={() => { paused = true }} on:mouseleave={() => { paused = false }}>
is `!== undefined` required here for clickable?

2021-09-02 15:14 UTC, 0c370t commented on src/atoms/Toast/Toast.svelte
> +        {#if content !== null && content !== undefined && content !== ""}
Just do a truthy check here

2021-09-02 15:14 UTC, 0c370t commented on src/atoms/Toast/ToastProvider/ToastProvider.svelte
> +    interface ToastRepresentation {
Can this be ToastModel or something more specific?

2021-09-07 23:31 UTC, zachstence commented on src/atoms/Toast/Toast.svelte
> +    if (configWithDefaults.onClose === null || configWithDefaults.onClose === undefined) configWithDefaults.onClose = DEFAULT_TOAST_CONFIG.onClose;
That was my initial thought, but when properties are provided in the config but specifically specified as `undefined`, they will not be overridden by the defaults. For example
```ts
const a = { key: undefined };
const b = { key: 123 };

const c = { ...a, ...b};
        = { key: undefined };
```
So unfortunately have to do it this kind of gross way.

2021-09-07 23:32 UTC, zachstence commented on src/atoms/Toast/Toast.svelte
> +<div class="toast {variant}" class:clickable={onClick !== undefined} on:click={onClick} on:mouseenter={() => { paused = true }} on:mouseleave={() => { paused = false }}>
Probably not, but I think its good for clarity in this case

2021-09-07 23:35 UTC, zachstence commented on src/atoms/Toast/ToastProvider/ToastProvider.svelte
> +    interface ToastRepresentation {
Resolved in 6a34614

2021-09-07 23:35 UTC, zachstence commented on src/atoms/Toast/ToastProvider/ToastProvider.stories.svelte
> +    // import "../../utils/Tailwind.css";
Resolved in 6a34614

2021-09-07 23:35 UTC, zachstence commented on src/atoms/Toast/Toast.svelte
> +        {#if content !== null && content !== undefined && content !== ""}
Resolved in 6a34614

2021-09-08 19:46 UTC, 0c370t approved these changes

2021-09-08 19:46 UTC, merged